# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scope & Craft | design and build with people
email: info@scopeandcraft.com
description: > # this means to ignore newlines until "baseurl:"
  Design and development for humans like you
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scopeandcraft.com" # the base hostname & protocol for your site
twitter_username: scopeandcraft
github_username:  scopeandcraft

# Build settings
markdown: kramdown
